name: WikiUpdateReadDelete

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
jobs:
  deploy:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Update Wiki
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}
        run: |
          # Set up your GitHub credentials
          git config --global user.email "ghaction@example.com"
          git config --global user.name "GH Action"

          # Clone the wiki repository
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.wiki.git repo.wiki
          cd repo.wiki

          # Create or update a wiki page
          echo "New content for the wiki page" > NewHome.md
          git add NewHome.md
          git commit -m "Update wiki page"
          git push
  cleanup:
    if: github.event_name == 'pull_request_target' && (github.event.pull_request.state == 'closed' || github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Download info from Wiki
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: wikiPage } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: `wiki/ReviewApp-${prNumber}.md`
            });
            const content = Buffer.from(wikiPage.content, 'base64').toString('utf8');
            console.log(content);
