name: WikiUpdateReadDelete

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
jobs:
  deploy:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions: # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    steps:
      - name: Checkout wiki
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
      - name: Update Wiki
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}
        run: |
          # Set up your GitHub credentials
          git config --global user.email "ghaction@example.com"
          git config --global user.name "GH Action"
          git config --global push.autoSetupRemote true

          git checkout -b doing-testing

          echo ${{ github.event.pull_request.head.ref }} > ${{ github.event.pull_request.number }}.md
          date +%s > last_update.md
          git add -A
          git commit -m "Update wiki page"
          git push
  cleanup:
    if: github.event_name == 'pull_request_target' && (github.event.pull_request.state == 'closed' || github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout wiki
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          branch: doing-testing
      - name: Read Wiki
        run: |
          echo ${{ github.event.pull_request.number }}
          cat ${{ github.event.pull_request.number }}.md
          
